apiVersion: xl-deploy/v1
kind: Applications
spec:
  - directory: Applications/backstage
    children:
      - name: test-cmd
        type: udm.Application
        children:
          - name: 2.0.0
            type: udm.DeploymentPackage
