apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-software-template
  annotations:
    dai-deploy/ci-id: appfolder1
spec:
  type: other
  lifecycle: production
  owner: user:default/sishwarya
