apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-register-deploy-application-cmd
  annotations:
    dai-deploy/ci-id: backstage-register-deploy-application-cmd
spec:
  type: service
  lifecycle: production
  owner: guests
